onboarding = false

[theme]
name = "catppuccin"

[experimental]
switch_ascii_input_source_in_prefix = true

[ui]
mouse_capture = true
prompt_new_tab_name = false
sidebar_start_collapsed = true
sidebar_collapsed_mode = "hidden"
agent_panel_sort = "spaces"
tab_bar_right = [
	{ type = "command", command = "~/.config/herdr/status.sh", interval_seconds = 5, timeout_seconds = 2 },
]

[ui.sidebar.spaces]
row_gap = 0
rows = [
  ["state_icon", "workspace"],
  ["branch", "git_status"],
]

[ui.sidebar.agents]
row_gap = 0
rows = [
  ["state_icon", { token = "agent", fg = "#89b4fa", bold = true, dim = false }, { token = "state_text", bold = true, dim = false }],
  [{ token = "workspace", fg = "#9399b2", bold = false, dim = false }, { token = "tab", fg = "#9399b2", bold = false, dim = false }]
]

[ui.toast]
delivery = "system"

[ui.toast.herdr]
position = "top-right"

[ui.sound]
enabled = false

[terminal]
default_shell = "/usr/bin/fish"
new_cwd = "follow"

[keys]
prefix = "ctrl+a"
reload_config = "prefix+r"
resize_mode = ""
goto = ""
new_tab = "ctrl+t"
switch_tab = "ctrl+1..9"
next_tab = "ctrl+tab"
close_pane = "ctrl+w"

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"

[[keys.command]]
key = "prefix+n"
type = "pane"
command = "nvim"
