require("config.options")
require("config.keymaps")
require("config.lazy")
require("config.lsp")
require("config.diagnostics")
require("config.snippets")
require("config.commands")

vim.cmd("colorscheme catppuccin-mocha")
vim.cmd.highlight("IndentLine guifg=#524f67")
vim.cmd.highlight("IndentLineCurrent guifg=#908caa")
