################### VISUAL ###################

position=top-right
offset_y=10

preset=-1

text_outline

### Color customization
text_color=CDD6F4
gpu_color=A6E3A1
cpu_color=89B4FA
vram_color=CBA6F7
ram_color=F5C2E7
engine_color=F38BA8
io_color=94E2D5
frametime_color=A6E3A1
background_color=1E1E2E
media_player_color=F2CDCD
wine_color=F38BA8
battery_color=FAB387
network_color=F5C2E7
horizontal_separator_color=585B70
background_alpha=0

fps_color_change
fps_color=F38BA8,F9E2AF,A6E3A1

################ INTERACTION #################

reload_cfg=Shift_R+R
toggle_hud=Shift_R+O
toggle_preset=Shift_R+T
