"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$character\
"""

add_newline = false

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[@](green bold)[$hostname](green bold):'
trim_at = "."
disabled = false

[character]                            
success_symbol = "[❯](bold blue)"
error_symbol = "[✗](bold red)"

[git_branch]
format = 'git:\([$branch]($style)\) '
style = "red bold"

[directory]
read_only = ""
truncation_symbol = "..."
truncation_length = 5
truncate_to_repo = false
style = "blue bold"