return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	build = ":TSUpdate",
	dependencies = {
		-- "nvim-treesitter/nvim-treesitter-textobjects",
	},
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"c_sharp",
			"diff",
			"html",
			"javascript",
			"jsdoc",
			"json",
			"jsonc",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"printf",
			"python",
			"query",
			"regex",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"go",
			"gdscript",
			"godot_resource",
			"gdshader",
		},
		sync_install = false,
		auto_install = true,
		indent = {
			enable = true,
		},
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = false,
		},
		playgrund = {
			enable = true,
		},
		-- textobjects = {
		-- 	select = {
		-- 		enable = true,
		-- 		lookahead = true,
		-- 		keymaps = {
		-- 			["af"] = "@function.outer",
		-- 			["if"] = "@function.inner",
		-- 			["ac"] = "@class.outer",
		-- 			["ic"] = "@class.inner",
		-- 		},
		-- 	},
		-- 	move = {
		-- 		enable = true,
		-- 		set_jumps = true,
		-- 		goto_next_start = {
		-- 			["]f"] = "@function.outer",
		-- 			["]c"] = "@class.outer",
		-- 		},
		-- 		goto_previous_start = {
		-- 			["[f"] = "@function.outer",
		-- 			["[c"] = "@class.outer",
		-- 		},
		-- 	},
		-- },
	},
}
