exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
exec-once = dms run
exec-once = swaync -c ~/.config/swaync/config.json -swb
exec-once = hyprctl setcursor Bibata-Modern-Ice, 24
exec-once = qs -c switcher
