# exec-once = hyprpaper
exec-once = awww-daemon
# exec-once = sleep 1 && ~/.config/scripts/wallpaper-switcher.py --restore
exec-once = hypridle
exec-once = qs -c shell
exec-once = qs -c switcher
exec-once = hyprctl setcursor Bibata-Modern-Ice, 24
