hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("qs -c shell")
	hl.exec_cmd("qs -c switcher")
end)
