# exec-once = hyprpaper
exec-once = systemctl --user start hyprland-session.target
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = awww-daemon
# exec-once = sleep 1 && ~/.config/scripts/wallpaper-switcher.py --restore
exec-once = hypridle
exec-once = qs -c shell
exec-once = qs -c switcher
exec-once = hyprctl setcursor Bibata-Modern-Ice, 24
