local mod = "ALT"

hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:272", hl.dsp.window.float(), { click = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("CTRL + E", hl.dsp.exec_cmd("alacritty"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("firefox"))
hl.bind("CTRL + space", hl.dsp.exec_cmd("pkill rofi || ~/.config/scripts/rofi-run.sh"))
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("~/.config/scripts/wallpaper-switcher.py"))
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("~/.config/scripts/mangohud-switcher.sh"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("nautilus"))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("CTRL + SHIFT + ESCAPE", hl.dsp.exec_cmd("wezterm start -- btop"))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))

hl.bind(mod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mod .. " + W", hl.dsp.window.close())
hl.bind(mod .. " + T", function()
	if hl.get_active_window().floating then
		hl.dispatch(hl.dsp.window.float())
	else
		hl.dispatch(hl.dsp.window.float())
		hl.dispatch(hl.dsp.window.resize({ x = 1600, y = 900 }))
		hl.dispatch(hl.dsp.window.center())
	end
end)

hl.bind(mod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + LEFT", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + RIGHT", hl.dsp.focus({ direction = "right" }))

hl.bind(mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
hl.bind(mod .. " + SHIFT + LEFT", hl.dsp.window.move({ direction = "left" }))
hl.bind(mod .. " + SHIFT + RIGHT", hl.dsp.window.move({ direction = "right" }))
hl.bind(mod .. " + SHIFT + UP", hl.dsp.window.move({ direction = "up" }))
hl.bind(mod .. " + SHIFT + DOWN", hl.dsp.window.move({ direction = "down" }))

hl.bind(mod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mod .. " + A", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mod .. " + D", hl.dsp.focus({ workspace = "r+1" }))

hl.bind(mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))

hl.bind(mod .. " + Q", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + Q", hl.dsp.window.move({ workspace = "+0" }))
hl.bind(mod .. " + Q", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + Q", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mod .. " + Q", hl.dsp.workspace.toggle_special("magic"))

hl.define_submap("resize", function()
	hl.bind("right", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
	hl.bind("left", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
	hl.bind("up", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })
	hl.bind("down", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
	hl.bind("escape", hl.dsp.submap("reset"))
	hl.bind(mod .. " + R", hl.dsp.submap("reset"))
end)
hl.bind(mod .. " + R", hl.dsp.submap("resize"))

hl.define_submap("pause", function()
	hl.bind(mod .. " + SHIFT + P", hl.dsp.submap("reset"))
end)
hl.bind(mod .. " + SHIFT + P", hl.dsp.submap("pause"))

hl.bind(mod .. " + TAB", hl.dsp.exec_cmd("qs ipc -c switcher call switcher open"))
hl.bind(mod .. " + TAB", hl.dsp.submap("pause"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("mouse:276", hl.dsp.pass({ window = "class:^(discord)$" }))
