binds {
    drag_threshold = 10
}

$mod = ALT

bindm = $mod, mouse:272, movewindow
bindc = $mod, mouse:272, togglefloating
bindm = $mod, mouse:273, resizewindow

bind = Ctrl_l, E, exec, wezterm
bind = SUPER, B, exec, firefox
bind = Ctrl_l, space, exec, pkill rofi || ~/.config/scripts/rofi-run.sh
bind = SUPER, E, exec, nautilus
bind = SUPER, D, exec, hypr-dock
bind = SUPER SHIFT, S, exec, hyprshot -m region
bind = Ctrl_l SHIFT, ESCAPE, exec, dms ipc call processlist toggle
bind = SUPER SHIFT, c, exec, hyprpicker -a

bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d
bind = $mod, LEFT, movefocus, l
bind = $mod, RIGHT, movefocus, r

bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, LEFT, movewindow, l
bind = $mod SHIFT, RIGHT, movewindow, r
bind = $mod SHIFT, UP, movewindow, u
bind = $mod SHIFT, DOWN, movewindow, d

bind = $mod, T, exec, ~/.config/scripts/toggle_floating.sh

bind = $mod SHIFT, SPACE, togglesplit
bind = $mod, V, togglesplit

bind = $mod, F, fullscreen
bind = $mod, W, killactive

bind = SUPER, D, exec, ~/.config/scripts/show_desktop.sh

bind = $mod, Q, togglespecialworkspace, magic
bind = $mod, Q, movetoworkspace, +0
bind = $mod, Q, togglespecialworkspace, magic
bind = $mod, Q, movetoworkspace, special:magic
bind = $mod, Q, togglespecialworkspace, magic

# bind = $mod SHIFT, Q, exec, hyprctl dispatch exit
bind = $mod SHIFT, R, exec, hyprctl reload
# bind = $mod SHIFT, E, exit

bind = $mod, A, workspace, r-1
bind = $mod, D, workspace, r+1

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9

bind = $mod, R, submap, resize
submap = resize
binde = , right, resizeactive, 20 0
binde = , left, resizeactive, -20 0
binde = , up, resizeactive, 0 -20
binde = , down, resizeactive, 0 20
bind = , escape, submap, reset
bind =  $mod, R, submap, reset
submap = reset

bind = $mod SHIFT, P, submap, pause
submap = pause
bind =  $mod SHIFT, P, submap, reset
submap = reset

# Fn keys
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# bind = $mod, Tab, cyclenext
# bind = $mod, Tab, bringactivetotop

bind = ,mouse:276, exec, ~/.config/scripts/toggle_mute.sh

bind = $mod, TAB, exec, qs ipc -c switcher call switcher open
bind = $mod, TAB, submap, pause
