# Ignore maximize requests from apps
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# WinBoat
windowrulev2 = suppressevent fullscreen maximize activate activatefocus, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = noinitialfocus, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = fullscreen, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = noanim, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = norounding, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = noborder, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = noshadow, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = noblur, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = xray 0, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = opaque, class:^(Microsoft Word|Microsoft Excel|Microsoft PowerPoint|Photoshop|File Explorer)$ windowrulev2 = opaque, class:^(wlfreerdp)$ windowrulev2 = xray 0, class:^(wlfreerdp)$

# windowrulev2 = opacity 0.95, class:^(Code)$
windowrulev2 = float,class:^(org.gnome.Nautilus)$
windowrulev2 = size 1400 800,class:^(org.gnome.Nautilus)$
windowrulev2 = stayfocused, class:^(Rofi)$
windowrulev2 = float,class:^(better-control.py)$
windowrulev2 = move 872 40,class:^(better_control.py)$
windowrulev2 = size 1041 536,class:^(better_control.py)$
windowrulev2 = float,class:^(org.gnome.SystemMonitor)$
windowrulev2 = size 1400 800,class:^(org.gnome.SystemMonitor)$
