# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

windowrule = opacity 0.95, match:class ^(code)$
windowrule = float on, size 1400 800, match:class ^(org.gnome.Nautilus)$
windowrule = stay_focused on, match:class ^(Rofi)$
windowrule = float on, match:class ^(better-control.py)$
windowrule = move (872) (40), size 1041 536, match:class ^(better_control.py)$
windowrule = float on, size 1400 800, match:class ^(org.gnome.SystemMonitor)$
windowrule = float on, size 1000 600, match:class ^(waypaper)$
