bind r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"

unbind C-b
set -g prefix C-a
set -g base-index 1
setw -g pane-base-index 1

set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 100000
set -g renumber-windows on
set -g allow-rename off
set -g set-clipboard on
set -g mode-keys vi

set -g mouse on
set -g default-terminal "tmux-256color"
set -g default-shell "/usr/bin/fish"
set -g default-command "/usr/bin/fish"
set -ag terminal-overrides ",xterm-256color:RGB,alacritty:RGB"

bind-key -n C-t new-window -c "#{pane_current_path}"
bind-key -n C-1 select-window -t :=1
bind-key -n C-2 select-window -t :=2
bind-key -n C-3 select-window -t :=3
bind-key -n C-4 select-window -t :=4
bind-key -n C-5 select-window -t :=5
bind-key -n C-6 select-window -t :=6
bind-key -n C-7 select-window -t :=7
bind-key -n C-8 select-window -t :=8
bind-key -n C-9 select-window -t :=9
bind-key -n C-Tab next-window
bind-key -n C-w kill-pane

bind-key "l" run-shell "sesh last"

bind-key "f" run-shell "sesh connect \"$(
  sesh list -t --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^t tmux ^x zoxide ^d kill ' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list -t --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

set -g @plugin "tmux-plugins/tpm"

set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'opencode lazygit'

set -g status on
set -g status-position top
set -g status-justify left

set -g status 2

set -g status-style "fg=white,bg=default"

set -g status-format[0] "#{E:status-left}#{W:#{E:window-status-format},#{E:window-status-current-format}}#[align=right]#{E:status-right}"
set -g status-format[1] ""

set -g status-left-length 40
set -g status-left "#[fg=#cba6f7,bg=#1e1e2e,fill=#1e1e2e]"

set -g status-right-length 180
set -g status-right "#[fg=#89b4fa,bg=default]#[fg=#11111b,bg=#89b4fa] #[fg=#cdd6f4,bg=#313244] #S #[fg=#313244,bg=default] #[fg=#a6e3a1,bg=default]#[fg=#11111b,bg=#a6e3a1]󰉋 #[fg=#cdd6f4,bg=#313244] #{=/32/...:pane_current_path} #[fg=#313244,bg=default]"

setw -g window-status-style "fg=white,bg=#1e1e2e"
setw -g window-status-format "#[fg=black,bg=#1e1e2e]#[fg=white,bg=black]#I #W#[fg=black,bg=#1e1e2e] "

setw -g window-status-current-style "fg=#1e1e2e,bg=blue"
setw -g window-status-current-format "#[fg=blue,bg=#1e1e2e]#[fg=#1e1e2e,bg=blue,bold]#I #W#[fg=blue,bg=#1e1e2e] "

setw -g window-status-bell-style "fg=#1e1e2e,bg=red,bold"

set -g message-style "fg=red,bg=#1e1e2e,bold"
set -g message-command-style "fg=#1e1e2e,bg=green,bold"

set -g pane-border-style "fg=black"
set -g pane-active-border-style "fg=blue"

run "~/.config/tmux/plugins/tpm/tpm"
